# This is a basic workflow to help you get started with Action

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # branches=$(yq '.scm.git.branches.name.[]' scmfile.yaml)
    #  echo credential.usernamePassword.password=${{ secrets.GITHUB_TOKEN }} >> scmfile.yaml
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create scmfile.yaml
        run: |
          touch scmfile.yaml

          password=$(yq '.credential.usernamePassword.password // "" ' scmfile.yaml) 
          username=$(yq '.credential.usernamePassword.username // "" ' scmfile.yaml) 
          url=$(yq '.scm.git.userRemoteConfig.url // "" ' scmfile.yaml) 

          echo $branches
          echo $password

          if [ "$password" == "" ]
          then
            yq '.credential.usernamePassword.password = ${{ secrets.GITHUB_TOKEN }}' scmfile.yaml
           
          fi

          if [ $username = "" ]
          then 
            echo credential.usernamePassword.username=${{ github.actor }} >> scmfile.yaml
          fi

          if [ $url = "" ]
          then 
            echo scm.git.userRemoteConfig.url=${{ github.repositoryUrl }} >> scmfile.yaml
          fi

          if [ $branchName = "null" ]
          then 
            echo scm.git.branches.name=${{ github.ref_name }} >> scmfile.yaml
          fi
          cat scmfile.yaml

      # - name: Replace scmfile.yaml With Custom Value
      #   uses: microsoft/variable-substitution@v1
      #   with:
      #     files: scmfile.yaml
      #   env:
      #     credential.usernamePassword.password: ${{ secrets.GITHUB_TOKEN }}
      #     credential.usernamePassword.username: ${{ github.actor }}
      #     scm.git.userRemoteConfig.url: ${{ github.repositoryUrl }}
      #     scm.git.branches.name: ${{ github.ref_name }}

      # Runs a set of commands using the runners shell
      # - name: custom runner github action
      #   uses: inspirit941/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master
      #   with:
      #     jenkinsfile: Jenkinsfile
      #     plugins: plugins.txt
      #     scmfile: scmfile.yaml
